services:
  db:
    image: postgres:15
    container_name: my_postgres_container
    environment:
      - POSTGRES_DB=myprojectdb
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
